name: Docker Image CI

on:
  push:
    branches: [vish198910 ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arjunbakshi245/lane_lines:$(date +%s)
      
    - name: Docker Push
      run: docker push --all-tags arjunbakshi245/lane_lines
      
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: After the recent commit ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: vishnu.sharma18@st.niituniversity.in, arjunbakshi245@gmail.com, yukta.sharma18@st.niituniversity.in, kawalnain.batra18@st.niituniversity.in, tanish.gupta18@st.niituniversity.in 
        # from email name
        from: Capstone2 Project
