# Generated by Django 4.0 on 2021-12-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lane_line_detector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
